package oogasalad.view.api.enums;

/**
 * Represents an event type; used to specify which type of handler should be added to nodes
 *
 * @author Jordan Haytaian
 */
public enum SceneElementEvent {
  START_LANGUAGE,
  START_TITLE,
  START_MENU,
  ADD_FRIEND,
  START_AUTHORING,
  START_NEW_GAME,
  START_SAVED_GAME,
  MANAGE_GAME,
  PAUSE,
  RESUME,
  SAVE,
  POWER_HEIGHT,
  SET_POWER,
  SET_ANGLE,
  NEXT_ROUND,
  SET_ROUND,
  SET_TURN,
  SET_SCORE,
  CHANGE_THEME,
  GAME_OVER,
  NEW_GAME_WINDOW,
  HELP,
  SET_ENGLISH,
  SET_SPANISH,
  SET_FRENCH,
  SET_HEBREW,
  START_LOGIN,
  LOGIN,
  CREATE_USER,
  USER_TEXT,
  PASSWORD_TEXT,
  LEADERBOARD,
  UPDATE_CURRENT_PLAYERS,
  CHANGE_MOD,
  LEADERBOARD_SCORES,
  PLAYER_PERMISSIONS,
  PLAYER_FRIENDS,
  SUBMIT_FRIENDS,
  SUBMIT_PERMISSIONS,
  SET_PUBLIC,
  AVATAR_SELECTION
}
